version: '3.8'
services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rbac
    ports:
      - '4000:5432'
  test_db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '4001:5432'
  backend:
    build: ./backend
    depends_on:
      - db
    command: sh -c "./wait-for-it.sh db:5432 --timeout=30 && ./db/init_db.sh"